services:
  mysql:
    image: mysql:8.0.45-debian
    container_name: assignMe_mysql
    environment:
      MYSQL_ROOT_PASSWORD: iusearchbtw
      MYSQL_USER: admin
      MYSQL_PASSWORD: Snowbell1!
      MYSQL_DATABASE: user_data
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
      build: .
      container_name: assignMe_django
      ports:
        - "8000:8000"
        - "80:80"
      volumes:
        - ../djangoproject:/usr/src/assignmentOrganizer/djangoproject
        - /webserver:/usr/src/assignmentOrganizer/webserver
      depends_on:
        - mysql

volumes:
  mysql_data: