# Generated by Django 5.2.12 on 2026-03-17 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('key', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=700)),
                ('course_id', models.CharField(blank=True, max_length=20, null=True)),
                ('filter', models.BooleanField(default=False)),
                ('isRow', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('key', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
            ],
            options={
                'db_table': 'assignments',
                'managed': True,
            },
        ),
    ]
