# Generated by Django 5.2.12 on 2026-03-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_assignments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
