# Generated by Django 5.2.12 on 2026-03-27 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assignments_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('headerImage', models.CharField(blank=True, max_length=700, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings',
                'managed': True,
            },
        ),
    ]
