# Generated by Django 5.2.12 on 2026-04-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('key', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=700, null=True)),
                ('url', models.CharField(blank=True, max_length=700, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('assignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assignments')),
            ],
            options={
                'db_table': 'modules',
                'managed': True,
            },
        ),
    ]
