# Generated by Django 5.2.12 on 2026-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='headerImage',
            field=models.CharField(blank=True, default='default', max_length=700, null=True),
        ),
    ]
