# Generated by Django 5.2.12 on 2026-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_settings_headerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='theme',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
