# Generated by Django 5.2.14 on 2026-06-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_settings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='dueRange',
            field=models.IntegerField(default=10, max_length=2),
        ),
    ]
